"""Create all models

Revision ID: a7d964a8041a
Revises: 496bfdf99108
Create Date: 2024-06-24 08:21:43.153683

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a7d964a8041a'
down_revision = '496bfdf99108'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
